// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: contractor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishWorkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Author string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Uri    string `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
}

func (x *PublishWorkRequest) Reset() {
	*x = PublishWorkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contractor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishWorkRequest) ProtoMessage() {}

func (x *PublishWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contractor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishWorkRequest.ProtoReflect.Descriptor instead.
func (*PublishWorkRequest) Descriptor() ([]byte, []int) {
	return file_contractor_proto_rawDescGZIP(), []int{0}
}

func (x *PublishWorkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PublishWorkRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PublishWorkRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type PublishWorkResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxHash string `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
}

func (x *PublishWorkResponce) Reset() {
	*x = PublishWorkResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contractor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishWorkResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishWorkResponce) ProtoMessage() {}

func (x *PublishWorkResponce) ProtoReflect() protoreflect.Message {
	mi := &file_contractor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishWorkResponce.ProtoReflect.Descriptor instead.
func (*PublishWorkResponce) Descriptor() ([]byte, []int) {
	return file_contractor_proto_rawDescGZIP(), []int{1}
}

func (x *PublishWorkResponce) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type TxStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxHash  string `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	ChainId string `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
}

func (x *TxStatusRequest) Reset() {
	*x = TxStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contractor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxStatusRequest) ProtoMessage() {}

func (x *TxStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contractor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxStatusRequest.ProtoReflect.Descriptor instead.
func (*TxStatusRequest) Descriptor() ([]byte, []int) {
	return file_contractor_proto_rawDescGZIP(), []int{2}
}

func (x *TxStatusRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *TxStatusRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

type TxStatusResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status       bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // 0 - Failed, 1 - Success
	RevertReason string `protobuf:"bytes,2,opt,name=revert_reason,json=revertReason,proto3" json:"revert_reason,omitempty"`
}

func (x *TxStatusResponce) Reset() {
	*x = TxStatusResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contractor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxStatusResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxStatusResponce) ProtoMessage() {}

func (x *TxStatusResponce) ProtoReflect() protoreflect.Message {
	mi := &file_contractor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxStatusResponce.ProtoReflect.Descriptor instead.
func (*TxStatusResponce) Descriptor() ([]byte, []int) {
	return file_contractor_proto_rawDescGZIP(), []int{3}
}

func (x *TxStatusResponce) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *TxStatusResponce) GetRevertReason() string {
	if x != nil {
		return x.RevertReason
	}
	return ""
}

var File_contractor_proto protoreflect.FileDescriptor

var file_contractor_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0d, 0x70, 0x70, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x22, 0x52, 0x0a, 0x12, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x57, 0x6f, 0x72, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x69, 0x22, 0x2e, 0x0a, 0x13, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x17, 0x0a, 0x07,
	0x74, 0x78, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74,
	0x78, 0x48, 0x61, 0x73, 0x68, 0x22, 0x45, 0x0a, 0x0f, 0x54, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x78, 0x5f, 0x68,
	0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73,
	0x68, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x22, 0x4f, 0x0a, 0x10,
	0x54, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x76, 0x65,
	0x72, 0x74, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x72, 0x65, 0x76, 0x65, 0x72, 0x74, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x32, 0xb7, 0x01,
	0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x54, 0x0a, 0x0b, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x57, 0x6f,
	0x72, 0x6b, 0x12, 0x21, 0x2e, 0x70, 0x70, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x70, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x57, 0x6f, 0x72,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x09, 0x47, 0x65, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x2e, 0x70, 0x70, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x54, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x70, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x54, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_contractor_proto_rawDescOnce sync.Once
	file_contractor_proto_rawDescData = file_contractor_proto_rawDesc
)

func file_contractor_proto_rawDescGZIP() []byte {
	file_contractor_proto_rawDescOnce.Do(func() {
		file_contractor_proto_rawDescData = protoimpl.X.CompressGZIP(file_contractor_proto_rawDescData)
	})
	return file_contractor_proto_rawDescData
}

var file_contractor_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_contractor_proto_goTypes = []interface{}{
	(*PublishWorkRequest)(nil),  // 0: pp.contractor.PublishWorkRequest
	(*PublishWorkResponce)(nil), // 1: pp.contractor.PublishWorkResponce
	(*TxStatusRequest)(nil),     // 2: pp.contractor.TxStatusRequest
	(*TxStatusResponce)(nil),    // 3: pp.contractor.TxStatusResponce
}
var file_contractor_proto_depIdxs = []int32{
	0, // 0: pp.contractor.ContractorService.PublishWork:input_type -> pp.contractor.PublishWorkRequest
	2, // 1: pp.contractor.ContractorService.GetStatus:input_type -> pp.contractor.TxStatusRequest
	1, // 2: pp.contractor.ContractorService.PublishWork:output_type -> pp.contractor.PublishWorkResponce
	3, // 3: pp.contractor.ContractorService.GetStatus:output_type -> pp.contractor.TxStatusResponce
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contractor_proto_init() }
func file_contractor_proto_init() {
	if File_contractor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_contractor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishWorkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contractor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishWorkResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contractor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contractor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxStatusResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_contractor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contractor_proto_goTypes,
		DependencyIndexes: file_contractor_proto_depIdxs,
		MessageInfos:      file_contractor_proto_msgTypes,
	}.Build()
	File_contractor_proto = out.File
	file_contractor_proto_rawDesc = nil
	file_contractor_proto_goTypes = nil
	file_contractor_proto_depIdxs = nil
}
