// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.3
// source: pdf-srv/pdf.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PdfServiceClient is the client API for PdfService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PdfServiceClient interface {
	MakeScientificPaper(ctx context.Context, in *ScientificPaperRequest, opts ...grpc.CallOption) (*ScientificPaperResponse, error)
	MakeScientificPaperLatex(ctx context.Context, in *ScientificPaperRequest, opts ...grpc.CallOption) (*ScientificPaperResponse, error)
}

type pdfServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPdfServiceClient(cc grpc.ClientConnInterface) PdfServiceClient {
	return &pdfServiceClient{cc}
}

func (c *pdfServiceClient) MakeScientificPaper(ctx context.Context, in *ScientificPaperRequest, opts ...grpc.CallOption) (*ScientificPaperResponse, error) {
	out := new(ScientificPaperResponse)
	err := c.cc.Invoke(ctx, "/pp.contractor.PdfService/MakeScientificPaper", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pdfServiceClient) MakeScientificPaperLatex(ctx context.Context, in *ScientificPaperRequest, opts ...grpc.CallOption) (*ScientificPaperResponse, error) {
	out := new(ScientificPaperResponse)
	err := c.cc.Invoke(ctx, "/pp.contractor.PdfService/MakeScientificPaperLatex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PdfServiceServer is the server API for PdfService service.
// All implementations must embed UnimplementedPdfServiceServer
// for forward compatibility
type PdfServiceServer interface {
	MakeScientificPaper(context.Context, *ScientificPaperRequest) (*ScientificPaperResponse, error)
	MakeScientificPaperLatex(context.Context, *ScientificPaperRequest) (*ScientificPaperResponse, error)
	mustEmbedUnimplementedPdfServiceServer()
}

// UnimplementedPdfServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPdfServiceServer struct {
}

func (UnimplementedPdfServiceServer) MakeScientificPaper(context.Context, *ScientificPaperRequest) (*ScientificPaperResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeScientificPaper not implemented")
}
func (UnimplementedPdfServiceServer) MakeScientificPaperLatex(context.Context, *ScientificPaperRequest) (*ScientificPaperResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeScientificPaperLatex not implemented")
}
func (UnimplementedPdfServiceServer) mustEmbedUnimplementedPdfServiceServer() {}

// UnsafePdfServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PdfServiceServer will
// result in compilation errors.
type UnsafePdfServiceServer interface {
	mustEmbedUnimplementedPdfServiceServer()
}

func RegisterPdfServiceServer(s grpc.ServiceRegistrar, srv PdfServiceServer) {
	s.RegisterService(&PdfService_ServiceDesc, srv)
}

func _PdfService_MakeScientificPaper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScientificPaperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PdfServiceServer).MakeScientificPaper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pp.contractor.PdfService/MakeScientificPaper",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PdfServiceServer).MakeScientificPaper(ctx, req.(*ScientificPaperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PdfService_MakeScientificPaperLatex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScientificPaperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PdfServiceServer).MakeScientificPaperLatex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pp.contractor.PdfService/MakeScientificPaperLatex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PdfServiceServer).MakeScientificPaperLatex(ctx, req.(*ScientificPaperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PdfService_ServiceDesc is the grpc.ServiceDesc for PdfService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PdfService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pp.contractor.PdfService",
	HandlerType: (*PdfServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MakeScientificPaper",
			Handler:    _PdfService_MakeScientificPaper_Handler,
		},
		{
			MethodName: "MakeScientificPaperLatex",
			Handler:    _PdfService_MakeScientificPaperLatex_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pdf-srv/pdf.proto",
}
