// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: education-verifier-srv/education_verifier.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	EducationVerifierService_Verify_FullMethodName = "/pp.contractor.EducationVerifierService/Verify"
)

// EducationVerifierServiceClient is the client API for EducationVerifierService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EducationVerifierServiceClient interface {
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
}

type educationVerifierServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEducationVerifierServiceClient(cc grpc.ClientConnInterface) EducationVerifierServiceClient {
	return &educationVerifierServiceClient{cc}
}

func (c *educationVerifierServiceClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, EducationVerifierService_Verify_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EducationVerifierServiceServer is the server API for EducationVerifierService service.
// All implementations must embed UnimplementedEducationVerifierServiceServer
// for forward compatibility
type EducationVerifierServiceServer interface {
	Verify(context.Context, *VerifyRequest) (*VerifyResponse, error)
	mustEmbedUnimplementedEducationVerifierServiceServer()
}

// UnimplementedEducationVerifierServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEducationVerifierServiceServer struct {
}

func (UnimplementedEducationVerifierServiceServer) Verify(context.Context, *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedEducationVerifierServiceServer) mustEmbedUnimplementedEducationVerifierServiceServer() {
}

// UnsafeEducationVerifierServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EducationVerifierServiceServer will
// result in compilation errors.
type UnsafeEducationVerifierServiceServer interface {
	mustEmbedUnimplementedEducationVerifierServiceServer()
}

func RegisterEducationVerifierServiceServer(s grpc.ServiceRegistrar, srv EducationVerifierServiceServer) {
	s.RegisterService(&EducationVerifierService_ServiceDesc, srv)
}

func _EducationVerifierService_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EducationVerifierServiceServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EducationVerifierService_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EducationVerifierServiceServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EducationVerifierService_ServiceDesc is the grpc.ServiceDesc for EducationVerifierService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EducationVerifierService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pp.contractor.EducationVerifierService",
	HandlerType: (*EducationVerifierServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Verify",
			Handler:    _EducationVerifierService_Verify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "education-verifier-srv/education_verifier.proto",
}
